### PR TITLE
Fixing use of css flexbox layout to work on Legacy player [stage-2]

### PR DESCRIPTION
**Pull request by stulees**
- Updating `circle.yml` to work with latest CCI build on 14.04
- Ensuring to use `-webkit` prefix for flex box css to support legacy

### CODE REVIEW

**Comment by stulees** [comment]
@donnapep @rodrigopavezi Please review, thanks

**Comment by donnapep** [comment]
@stulees I think `justify-content` needs a `-webkit-` prefix. It's a flexbox property too.

**Comment by stulees** [comment]
@donnapep Weird, I could have sworn I included that. Have added it now, thanks.

**Comment by donnapep** [comment]
👍

**Pull request merged**
